#!/usr/bin/python3
# -*- Mode: python; coding: utf-8  -*-
# helloWorld

from gi.repository import Gtk
import sys

class MyWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title='Hello World')
        self.button = Gtk.Button(label='Quit')
        self.button.connect('clicked', self.on_button_clicked)
        self.add(self.button)
        self.connect_after('destroy', self.destroy)

    def on_button_clicked(self, widget):
        self.destroy()

    def destroy(self, widget = None):
        Gtk.main_quit()

def main():
    win = MyWindow()
    win.connect('delete-event', Gtk.main_quit)
    win.show_all()
    Gtk.main()

if __name__ == '__main__':
    sys.exit(main())

